name: $(Build.DefinitionName)_1.0.$(year:yy)$(DayOfYear)$(Rev:.r)
trigger:
  branches:
    include:
    - main
    exclude:
    - .github\workflows\workflow.yaml
    - roles.azcli
    - roles.txt
pool:
  name: Azure Pipelines

variables:
  azureResourceManagerConnection: '$(variables.azureResourceManagerConnection)'

stages:
- stage: Build 
  jobs:
  - job: Build 
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: md AzureDeployFiles
      displayName: create output directory
      workingDirectory: $(System.DefaultWorkingDirectory)

    - task: AzureCLI@2
      displayName: 'Azure CLI '
      inputs:
        azureSubscription: '$(azureResourceManagerConnection)'
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: 'az bicep build --file "Bicep Samples/sharedAppConfig.bicep" --outdir $(System.DefaultWorkingDirectory)/AzureDeployFiles'

    - task: CopyFiles@2
      displayName: 'Copy ARM Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/AzureDeployFiles'
        Contents: sharedAppConfig.json
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true

    - task: AzureCLI@2
      displayName: 'Azure CLI '
      inputs:
        azureSubscription: '$(azureResourceManagerConnection)'
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: 'az bicep build --file "Bicep Samples/sharedResourceManager.bicep" --outdir $(System.DefaultWorkingDirectory)/AzureDeployFiles'

    - task: CopyFiles@2
      displayName: 'Copy ARM Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/AzureDeployFiles'
        Contents: sharedResourceManager.json
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: false

    - task: AzureCLI@2
      displayName: 'Azure CLI '
      inputs:
        azureSubscription: '$(azureResourceManagerConnection)'
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: 'az bicep build --file "Bicep Samples/environment.bicep" --outdir $(System.DefaultWorkingDirectory)/AzureDeployFiles'

    - task: CopyFiles@2
      displayName: 'Copy ARM Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/AzureDeployFiles'
        Contents: environment.json
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: false

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: ARM'
      inputs:
        ArtifactName: ARM
