name: Build Bicep Files

on:
  workflow_dispatch:
  push:
    branches: 'main'

permissions:
  id-token: write

env:
  OCTOPUS_SPACE: Default

# az ad sp create-for-rbac --name ghaCloudIntegrationTraining --role contributor --scopes /subscriptions/xxx/resourceGroups/CloudIntegrationTraining --sdk-auth
jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version-generator.outputs.version }}

    steps:

      # Checkout code
    - uses: actions/checkout@v2

    - name: Login to Octopus Deploy 
      uses: OctopusDeploy/login@v1
      with: 
        server: https://biztalkbill.octopus.app
        service_account_id: 966ed2db-5519-4b1c-aece-2fcf43c46837

    - name: Set Version Number
      id: version-generator
      run: echo "version=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT

    - name: Create artifacts folder
      run: |
        mkdir "$GITHUB_WORKSPACE/artifacts"
        mkdir "$GITHUB_WORKSPACE/artifacts/ARM"

      # Log into Azure
    - uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
        enable-AzPSSession: true

      # build Bicep file
    - name: Azure CLI script file
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: 'az bicep build --file "Bicep Samples/sharedAppConfig.bicep" --outdir $GITHUB_WORKSPACE/artifacts/ARM'

      # build Bicep file
    - name: Azure CLI script file
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: 'az bicep build --file "Bicep Samples/environmentBase.bicep"  --outdir $GITHUB_WORKSPACE/artifacts/ARM'

      # build Bicep file
    - name: Azure CLI script file
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: 'az bicep build --file "Bicep Samples/environment.bicep"  --outdir $GITHUB_WORKSPACE/artifacts/ARM'

    - name: Package ARM 🐙
      uses: OctopusDeploy/create-zip-package-action@v3
      with:
        package_id: "ARMTemplates"
        version: "${{ steps.version-generator.outputs.version }}"
        output_folder: "${{ github.workspace }}/artifacts"
        base_path: "${{ github.workspace }}/artifacts/ARM"
        files: |
          **/*.*