name: Build Bicep Files

on:
  workflow_dispatch:
  push:
    branches: 'main'

# az ad sp create-for-rbac --name ghaCloudIntegrationTraining --role contributor --scopes /subscriptions/xxx/resourceGroups/CloudIntegrationTraining --sdk-auth
jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version-generator.outputs.version }}

    steps:

      # Checkout code
    - uses: actions/checkout@main

    - name: Set version 
      run: echo "PACKAGE_VERSION=1.0.$(date +%Y%m%d).$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

    - name: Create artifacts folder
      run: |
        mkdir "$GITHUB_WORKSPACE/artifacts"
        mkdir "$GITHUB_WORKSPACE/artifacts/ARM"

      # Log into Azure
    - uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
        enable-AzPSSession: true

      # build Bicep file
    - name: Azure CLI script file
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: 'az bicep build --file "Bicep Samples/appconfiguration.bicep" --outdir $GITHUB_WORKSPACE/artifacts/ARM'

      # build Bicep file
    - name: Azure CLI script file
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: 'az bicep build --file "Bicep Samples/keyvault.bicep"  --outdir $GITHUB_WORKSPACE/artifacts/ARM'

      # build Bicep file
    - name: Azure CLI script file
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: 'az bicep build --file "Bicep Samples/apimanagemenbase.bicep"  --outdir $GITHUB_WORKSPACE/artifacts/ARM'
